/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course_Management_System;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class AssignmentStudentPage extends javax.swing.JFrame {

    /**
     * Creates new form AssignmentPage
     */
    public AssignmentStudentPage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(0, 204, 204));
        jList1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Assignment1", "Assignmnet2", "Assignment3", "Assignment4", "Assignment5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 240, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Assignments:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText(" Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText(" LogOut");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Owner\\Desktop\\login-background-images-png.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<Course> ASP = new ArrayList();
    Student s4;
    ArrayList<Assignment> assignArray = new ArrayList();
    ArrayList<String> resourcesCourse = new ArrayList();
    String fileName;
    String CourseSelec;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if(jList1.isSelectionEmpty()){
                JOptionPane.showMessageDialog(AssignmentStudentPage.this, "No Assignment is Selected");
            }
            else{
                this.dispose();
      String a =  jList1.getSelectedValue();
      AssignmentDetailsForm assignmentForm = new AssignmentDetailsForm();
      assignmentForm.resCourse = resourcesCourse;
      assignmentForm.stud = s4;
      assignmentForm.arr = ASP;
      assignmentForm.arrayAssign = assignArray;
      for(int i = 0;i < assignArray.size();i++){
          if(a.equals(assignArray.get(i).assignmentName)){
              String CourseName = assignArray.get(i).CourseName;
              String assignmentName = assignArray.get(i).assignmentName;
              assignmentForm.jLabel8.setText(CourseName);
              assignmentForm.jLabel9.setText(assignmentName);
              assignmentForm.jLabel10.setText("" + assignArray.get(i).AssignmentMarks);
              assignmentForm.jLabel11.setText(assignArray.get(i).DueDate);
              assignmentForm.jLabel12.setText(assignArray.get(i).dueTime);
              FileInputStream fstream = new FileInputStream(CourseName + "/" + CourseName + assignmentName + ".dat");
              DataInputStream datastream = new DataInputStream(fstream);
                       fileName = datastream.readUTF();
                       fstream.close();
                       datastream.close();
                      assignmentForm.filename = fileName;
                      assignmentForm.jLabel7.setText(fileName);
                      assignmentForm.CourseSelected = CourseSelec;
                      File file = new File(s4.ID + CourseSelec + "/" + a + ".dat");
                      if(file.exists()){
                           FileInputStream instream = new FileInputStream(file);
                      DataInputStream datstream = new DataInputStream(instream);
                      assignmentForm.jLabel15.setText(datstream.readUTF());
                      instream.close();
                      datstream.close();
                      File file2 = new File(CourseName + "Submission" + "/" + assignmentName + "/" + s4.ID + "/" + "Graded.dat");
                      if(file2.exists()){
                          FileInputStream stream = new FileInputStream(file2);
                      DataInputStream dstream = new DataInputStream(stream);
                      String marks = dstream.readUTF();
                      stream.close();
                      dstream.close();
                      assignmentForm.jLabel17.setText(marks);
                      }
                      File file3 = new File(CourseName + "Submission" + "/" + assignmentName + "/" + s4.ID + "/" + "attachment.dat");
                      if(file3.exists()){
                           FileInputStream stream = new FileInputStream(file3);
                      DataInputStream dstream = new DataInputStream(stream);
                      String attachmentName = dstream.readUTF();
                      stream.close();
                      dstream.close();
                      assignmentForm.jLabel18.setText(attachmentName);
                      }
                      break;  
                    }         
          }
      }
      assignmentForm.setVisible(true);
            }
              
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(AssignmentStudentPage.this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
         this.dispose();
         CoursePage2 coursepage2 = new CoursePage2();
         coursepage2.courseResource = resourcesCourse;
         coursepage2.selecCourse = CourseSelec;
         coursepage2.s3 = s4;
         coursepage2.coursesArr = ASP;
         coursepage2.assignmentArray = assignArray;
          coursepage2.setVisible(true);
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new CMS_MainPage().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentStudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentStudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentStudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentStudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentStudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
