/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course_Management_System;

import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Owner
 */
public class Student_MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Student_MainPage
     */
    
    public Student_MainPage() {
        initComponents();
    }
    
    Student student1;
    ArrayList<Course> SMP = new ArrayList();

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText(" Courses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Menu:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText(" LogOut");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText("FeedBack");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setText(" Class Schedule");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Owner\\Desktop\\login-background-images-png.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("StudentCourse.dat");
             
            if(file.exists()){
                FileInputStream instream = new FileInputStream(file);
                ObjectInputStream obStream = new ObjectInputStream(instream);
                HashMap<String,ArrayList<Course>> map1 = (HashMap<String,ArrayList<Course>>)obStream.readObject();
                if(map1.containsKey(student1.ID)){
                    SMP = map1.get(student1.ID);
                  instream.close();
                  obStream.close();
                
             this.dispose();
         CoursePage coursepage = new CoursePage();
         coursepage.s2 = student1;
         coursepage.arrayCourse = SMP;
          
         DefaultListModel lm = new DefaultListModel();
         for(int i = 0;i < SMP.size();i++){
             lm.addElement(SMP.get(i).CourseName);
         }
         coursepage.jList1.setModel(lm);
        coursepage.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(Student_MainPage.this,"Student Has Not Been Assigned Any Courses Yet");
                }     
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Student_MainPage.this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new CMS_MainPage().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
        try{
            File file = new File("StudentCourse.dat");           
            if(file.exists()){
                FileInputStream instream = new FileInputStream(file);
                ObjectInputStream obStream = new ObjectInputStream(instream);
                HashMap<String,ArrayList<Course>> map1 = (HashMap<String,ArrayList<Course>>)obStream.readObject();
                 instream.close();
                  obStream.close();  
                if(map1.containsKey(student1.ID)){
                    this.dispose();
                    SMP = map1.get(student1.ID);
                  
                  TeacherFeedBackForm feedbackForm = new TeacherFeedBackForm();
               feedbackForm.arrCourse = SMP;
               feedbackForm.student = student1;
               DefaultComboBoxModel lm = new DefaultComboBoxModel();
               lm.addElement("Select");
         for(int i = 0;i < SMP.size();i++){
             lm.addElement(SMP.get(i).CourseName);
         }
           feedbackForm.jComboBox1.setModel(lm);
               feedbackForm.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(Student_MainPage.this,"Student Has Not Been Assigned Any Courses Yet");
                }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Student_MainPage.this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HashMap<String,ArrayList<Course>> map = new HashMap();
         StudentClassSchedule scheduleform = new StudentClassSchedule();
          try{
             File file = new File("StudentCourse.dat");
         if(file.exists()){
             FileInputStream stream = new FileInputStream(file);
             ObjectInputStream obstream = new ObjectInputStream(stream);
             map = (HashMap<String,ArrayList<Course>>)obstream.readObject();
             stream.close();
             obstream.close();
             if(map.containsKey(student1.ID)){
                 SMP = map.get(student1.ID);
                 scheduleform.s1 = student1;
                 scheduleform.arrayCourse = SMP;
                 DefaultTableModel tm = new DefaultTableModel();
                 Vector<String> vector = new Vector();
                  Vector<String> vector1 = new Vector();
                 for(int i = 0;i < SMP.size();i++){
                     vector.add(SMP.get(i).CourseName);
                     vector1.add(SMP.get(i).TimeSlot);
                 }
                 tm.addColumn("Course Name",vector);
                 tm.addColumn("Timings",vector1);
                 scheduleform.jTable1.setModel(tm);
             }
             else{
                 JOptionPane.showMessageDialog(Student_MainPage.this,"Student Has Not Been Assigned Any Courses Yet");
             }
         }
         scheduleform.setVisible(true); 
          }
          catch(Exception e){
              JOptionPane.showMessageDialog(Student_MainPage.this, e.getMessage());
          } 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
