/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course_Management_System;

import java.awt.List;
import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class Teacher_MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_MainPage
     */
    public Teacher_MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText(" Post Assignment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 190, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText(" Resources");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText(" Menu:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setText(" Assignments Received");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 204));
        jButton5.setText(" LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText(" Student Feedback");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Owner\\Desktop\\login-background-images-png.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     Teacher t1;
    
     
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HashMap<String,ArrayList<Course>> mp = new HashMap();
         
        try{
             AssignmentTeacherPage assignmentTeacher = new AssignmentTeacherPage();
          
         File file = new File("TeacherCourse.dat");
         if(file.exists()){
             FileInputStream instream = new FileInputStream(file);
             ObjectInputStream obstream = new ObjectInputStream(instream);
             mp = (HashMap<String,ArrayList<Course>>) obstream.readObject();
             instream.close();
             obstream.close();
             if(mp.containsKey(t1.ID)){
                 this.dispose();
                 t1.ArrayCourse = mp.get(t1.ID);
              assignmentTeacher.t2 = t1;
              assignmentTeacher.t2.ArrayCourse = t1.ArrayCourse;
             DefaultComboBoxModel model = new DefaultComboBoxModel();
             model.addElement("Select");
             for(int i = 0;i < t1.ArrayCourse.size();i++){
                 model.addElement( t1.ArrayCourse.get(i).CourseName);
             }
        assignmentTeacher.jComboBox1.setModel(model);
        assignmentTeacher.setVisible(true);
             }
             else{
                  JOptionPane.showMessageDialog(Teacher_MainPage.this, "Teacher Has Not Been Assigned Any Courses");
             }
              
         }   
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Teacher_MainPage.this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HashMap<String,ArrayList<Course>> mp = new HashMap();
         
        try{
             ResourcesTeacherPage resourcesTeacher = new ResourcesTeacherPage();
        resourcesTeacher.t4 = t1;
         
         File file = new File("TeacherCourse.dat");
         if(file.exists()){
             FileInputStream instream = new FileInputStream(file);
             ObjectInputStream obstream = new ObjectInputStream(instream);
             mp = (HashMap<String,ArrayList<Course>>) obstream.readObject();
             instream.close();
             obstream.close();
             if(mp.containsKey(t1.ID)){
                 this.dispose();
                 t1.ArrayCourse = mp.get(t1.ID);
             resourcesTeacher.t4.ArrayCourse = t1.ArrayCourse;
             DefaultComboBoxModel model = new DefaultComboBoxModel();
             model.addElement("Select");
             for(int i = 0;i < t1.ArrayCourse.size();i++){
                 model.addElement( t1.ArrayCourse.get(i).CourseName);
             }
             resourcesTeacher.jComboBox1.setModel(model);
        resourcesTeacher.setVisible(true);
             }
             else{
                 JOptionPane.showMessageDialog(Teacher_MainPage.this,"Teacher Has Not Been Assigned Any Courses");
             }
              
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Teacher_MainPage.this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new CMS_MainPage().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try{
            AssignmentsReceivedTeacher assignmentsReceived = new AssignmentsReceivedTeacher();
             HashMap<String,ArrayList<Course>> mp = new HashMap();
         
        File file = new File("TeacherCourse.dat");
         if(file.exists()){               
             FileInputStream instream = new FileInputStream(file);
             ObjectInputStream obstream = new ObjectInputStream(instream);
             mp = (HashMap<String,ArrayList<Course>>)obstream.readObject();
             instream.close();
             obstream.close();
             if(mp.containsKey(t1.ID)){
                 this.dispose();
                  t1.ArrayCourse = mp.get(t1.ID);
              assignmentsReceived.teacher = t1;
              assignmentsReceived.teacher.ArrayCourse = t1.ArrayCourse;
             DefaultComboBoxModel model = new DefaultComboBoxModel();
             model.addElement("Select");
             for(int i = 0;i < t1.ArrayCourse.size();i++){
                 model.addElement( t1.ArrayCourse.get(i).CourseName);
             }
             assignmentsReceived.jComboBox1.setModel(model);
              
             assignmentsReceived.setVisible(true);
             }
             else{
                 JOptionPane.showMessageDialog(Teacher_MainPage.this, "Teacher Has Not Been Assigned Any Courses");
             }
             
        
         }
      }
        catch(Exception e){
            JOptionPane.showMessageDialog(Teacher_MainPage.this, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            HashMap<String,ArrayList<Course>> mp = new HashMap();
            File file = new File("TeacherCourse.dat");
         if(file.exists()){
             FileInputStream instream = new FileInputStream(file);
             ObjectInputStream obstream = new ObjectInputStream(instream);
             mp = (HashMap<String,ArrayList<Course>>) obstream.readObject();
             instream.close();
             obstream.close();
             if(mp.containsKey(t1.ID)){
                 this.dispose();
                 t1.ArrayCourse = mp.get(t1.ID);
               
             DefaultComboBoxModel model = new DefaultComboBoxModel();
             model.addElement("Select");
             for(int i = 0;i < t1.ArrayCourse.size();i++){
                 model.addElement( t1.ArrayCourse.get(i).CourseName);
             }
        FeedBackReceivedForm feedbackForm = new FeedBackReceivedForm();
        feedbackForm.teach = t1;
        feedbackForm.teach.ArrayCourse = t1.ArrayCourse;
        feedbackForm.jComboBox1.setModel(model);
        feedbackForm.setVisible(true);
        }
         }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Teacher_MainPage.this, e.getMessage());
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
